# SwiftLint Configuration for MirageKit
# Aligned with AGENTS.md coding guidelines
# This is the primary config; Mirage root extends it via parent_config

# Paths for standalone MirageKit linting
included:
  - Sources
  - Tests

# Paths to exclude
excluded:
  - .build

# Analyzer rules (require compilation)
analyzer_rules:
  - unused_import

# Opt-in rules
opt_in_rules:
  - closure_spacing
  - force_try
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_comma  # SwiftFormat handles this
  - opening_brace   # SwiftFormat handles this
  - statement_position  # SwiftFormat handles this
  - todo  # Allow TODOs in development
  - modifier_order  # SwiftFormat handles this and has authoritative ordering
  - force_unwrapping  # Prefer Xcode defaults; avoid blocking on legacy call sites
  - force_cast  # Prefer Xcode defaults; avoid blocking on legacy call sites
  - closure_parameter_position
  - empty_string
  - for_where
  - large_tuple
  - legacy_multiple
  - legacy_random
  - multiple_closures_with_trailing_closure
  - non_optional_string_data_conversion
  - orphaned_doc_comment
  - unused_optional_binding

# Rule configurations

# Line length: 120 warning, 200 error (generous for complex SwiftUI modifiers)
line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

# File length: 500 lines target per AGENTS.md
file_length:
  warning: 700
  error: 900
  ignore_comment_only_lines: true

# Type body length
type_body_length:
  warning: 650
  error: 800

# Function body length
function_body_length:
  warning: 220
  error: 260

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 80
  error: 120

# Nesting level
nesting:
  type_level: 2
  function_level: 3

# Identifier name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - _id
    - e
    - h
    - s
    - x
    - y
    - z
    - i
    - j
    - k
    - ok
    - to
    - at
    - a
    - b
    - w

# Function parameter count
function_parameter_count:
  warning: 15
  error: 20

# Force try - warn per AGENTS.md
force_try:
  severity: warning

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Custom rules for AGENTS.md guidelines
custom_rules:
  # Discourage cornerRadius per AGENTS.md
  use_clip_shape:
    name: "Use clipShape"
    regex: '\.cornerRadius\s*\('
    message: "Use .clipShape(.rect(cornerRadius:)) instead of .cornerRadius()"
    severity: warning

  # Discourage ObservableObject per AGENTS.md
  no_observable_object:
    name: "No ObservableObject"
    regex: ':\s*ObservableObject\b'
    message: "Use @Observable macro instead of ObservableObject protocol"
    severity: warning
